### ISSUE TITLE
README file update

### ISSUE THREAD

**Issue by Thanus-Kumaar** [Thanus-Kumaar/FC-TeamForge-server#4]
### Requirements
Create a well-structured and good-looking README.md file for the backed repository. Be sure to use emojis and attach the link to the frontend repo without fail.
**Be Creative 🎨**

**Comment by BIJJUDAMA** [comment]
I would like to take this issue @Thanus-Kumaar

**Comment by Thanus-Kumaar** [comment]
Ok, you can work on this issue. @BIJJUDAMA
