### ISSUE TITLE
Database initialization.

### ISSUE THREAD

**Issue by Thanus-Kumaar** [Thanus-Kumaar/FC-TeamForge-server#6]
### Requirements

> [!IMPORTANT]
> High priority issue 

There is no database schema initialization present in the codebase. I am sharing the tables and `table descriptions` here.
Create the database init file and run it once after starting the server.
Very important to do it in a scalable manner. If possible, add schema diagram as a image in a folder called docs too.

Tables :
![{EF6D0E9B-22C7-4988-BDB7-087FB7489590}](https://github.com/user-attachments/assets/1bf068f7-fae0-45ad-9bb4-ae3872d0e90e)

Description of `players` table :
![{A3A1101A-11B3-45E0-8338-8A6424C6ED81}](https://github.com/user-attachments/assets/2bb59b3d-38ff-4ea3-96bb-bc7d197cbc3c)

Description of `formations` table :
![{66A3D785-A002-44C4-B7DC-CFF0B8CDBCE0}](https://github.com/user-attachments/assets/d752a814-3698-4c02-9dfc-5663dfc70ece)

**Comment by thecodingvivek** [comment]
1)As we are working on this project locally just try to install mysql  on your local machine. you can checkout this link .To install :  https://www.youtube.com/watch?v=BxdSUGBs0gM  

2)create tables with schemas
***example in mysql command line***
![image](https://github.com/user-attachments/assets/d3239354-3687-4e95-96fe-0d984ff289e3)

3)add database credentials in ***sqlconnect.js***
![image](https://github.com/user-attachments/assets/e1b96932-ad37-4860-9c3c-43d78da18826)

4)Create an account in ngrok. https://ngrok.com/  and copy the ***authtoken***  and  add it your .env file
***in server.js***
![image](https://github.com/user-attachments/assets/7554bbb3-6e3a-47dc-9e5a-bddd20f0a1e9)

5)Try running the server You should should see Something like this in your terminal
![image](https://github.com/user-attachments/assets/d395dbe3-011b-4e5f-a1cb-208d2e00d328)

6)Now add the url shown in the terminal to your ***constants.js*** file
![image](https://github.com/user-attachments/assets/6045e573-72b2-43b3-9f60-c9c80d5f1388)

7)You will now get a cors error so add header to allow requests from all origins: res.header("Access-Control-Allow-Origin", "*");
![image](https://github.com/user-attachments/assets/0622522f-bb3c-4980-83ee-1e249b43c707)


8)Your fine to go now.***HOPE THIS HELPS :)***


@Thanus-Kumaar
@TharunKumarrA

**Comment by TharunKumarrA** [comment]
Thank you @thecodingvivek for your help. Anyone who ate facing backend Integration problem can follow his steps until someone takes up this issue of creating the schema.sql

**Comment by Kirethik** [comment]
I would like to work on this issue @Thanus-Kumaar
